apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: yaml-linter-pipeline
spec:
    workspaces:
    - name: pipeline-share-data
  tasks:
    - name: clone-repository
      taskRef:
        name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-share-data
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-cohort/daniele-scaramuzzi-pipeline-assignment-problem2.git
        - name: revision
          value: "main"
    - name: yaml-lint-run #lint yaml
      taskRef:
        name: yaml-lint
      runAfter:
        - clone-repository
      workspaces:
        - name: shared-workspace
          workspace: pipeline-share-data
      params:
        - name: args
          value: ["."]